/**
 * MIT License
 *
 * Copyright (c) 2023, Brion Mario.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import {DEFAULT_MEDMARK_REGISTRY_FILENAME, MEDMARK_REGISTRY_VERSION} from './constants';
import logger from './logger';
import {MedmarkOptions, MedmarkRegistryFormat} from './models/medmark/core';
import {MedmarkFrontMatterAuthor} from './models/medmark/front-matter';
import {
  MedmarkRegistry,
  MedmarkRegistryContext,
  MedmarkRegistryEntry,
  MedmarkRegistryEntryContext,
  MedmarkRegistryFile,
} from './models/medmark/registry';
import {MedmarkTemplateRenderOptions} from './models/medmark/template';

/**
 * Escapes a string for safe inclusion in XML content.
 *
 * @param value - The raw string.
 * @returns The XML-escaped string.
 */
function escapeXml(value: string = ''): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Joins a base URL and a path segment without duplicating slashes.
 *
 * @param base - The base URL (e.g. `https://example.com`).
 * @param segment - The path segment (e.g. `/posts/foo`).
 * @returns The joined URL.
 */
function joinUrl(base: string, segment: string): string {
  return `${base.replace(/\/+$/, '')}/${segment.replace(/^\/+/, '')}`;
}

/**
 * Builds the default registry entry for a post. Exposed so userland templates
 * can reuse or extend it inside their own `buildRegistryEntry` hook.
 *
 * @param post - The render options for the post.
 * @param context - Context about where the post was written.
 * @returns The registry entry.
 */
export function buildDefaultRegistryEntry(
  post: MedmarkTemplateRenderOptions,
  context: MedmarkRegistryEntryContext,
): MedmarkRegistryEntry {
  const date: string | undefined = post.published ? new Date(post.published).toISOString().split('T')[0] : undefined;

  const bannerImage: string | undefined = post.images?.[0]?.mediumUrl;

  return {
    authors: (post.authors ?? []).map((author: MedmarkFrontMatterAuthor) => author.name),
    bannerImage,
    categories: post.categories,
    date,
    description: post.description,
    draft: post.draft,
    path: context.relativePath,
    readingTime: post.readingTime,
    slug: context.slug,
    source: {
      provider: 'medium',
      url: post.canonicalUrl,
    },
    tags: post.tags,
    title: post.title,
  };
}

/**
 * Serializes the registry as a `registry.json` manifest.
 */
function serializeAsJson(registry: MedmarkRegistry, filename: string): MedmarkRegistryFile {
  return {
    content: `${JSON.stringify(registry, null, 2)}\n`,
    filename: `${filename}.json`,
  };
}

/**
 * Serializes the registry as a typed `registry.ts` ESM module.
 */
function serializeAsTs(registry: MedmarkRegistry, filename: string): MedmarkRegistryFile {
  const content: string = `\
/* eslint-disable */
// This file is auto-generated by medmark. Do not edit manually.

export interface MedmarkRegistryEntry {
  authors?: string[];
  bannerImage?: string;
  categories?: string[];
  date?: string;
  description?: string;
  draft?: boolean;
  path: string;
  readingTime?: string;
  slug: string;
  source?: { provider: string; url?: string };
  tags?: string[];
  title: string;
}

export const generatedAt = ${JSON.stringify(registry.generatedAt)} as const;
export const generator = ${JSON.stringify(registry.generator)} as const;

const registry: MedmarkRegistryEntry[] = ${JSON.stringify(registry.posts, null, 2)};

export default registry;
`;

  return {
    content,
    filename: `${filename}.ts`,
  };
}

/**
 * Serializes the registry as an RSS 2.0 feed. Requires `site.url`.
 */
function serializeAsRss(registry: MedmarkRegistry, options: MedmarkOptions): MedmarkRegistryFile | null {
  const site = options.registry?.site;

  if (!site?.url) {
    logger.warn('Skipping RSS feed generation: `registry.site.url` is not configured.');
    return null;
  }

  const includeDrafts: boolean = options.registry?.includeDrafts ?? false;
  const posts: MedmarkRegistryEntry[] = registry.posts.filter(
    (post: MedmarkRegistryEntry) => includeDrafts || !post.draft,
  );

  const items: string = posts
    .map((post: MedmarkRegistryEntry) => {
      const link: string = joinUrl(site.url!, post.slug);
      const pubDate: string = post.date ? new Date(post.date).toUTCString() : '';

      return `    <item>
      <title>${escapeXml(post.title)}</title>
      <link>${escapeXml(link)}</link>
      <guid isPermaLink="true">${escapeXml(link)}</guid>
      ${pubDate ? `<pubDate>${pubDate}</pubDate>` : ''}
      <description>${escapeXml(post.description)}</description>
    </item>`;
    })
    .join('\n');

  const content: string = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>${escapeXml(site.title ?? '')}</title>
    <link>${escapeXml(site.url)}</link>
    <description>${escapeXml(site.description ?? '')}</description>
    ${site.language ? `<language>${escapeXml(site.language)}</language>` : ''}
${items}
  </channel>
</rss>
`;

  return {
    content,
    filename: 'feed.xml',
  };
}

/**
 * Serializes the registry as a `sitemap.xml`. Requires `site.url`.
 */
function serializeAsSitemap(registry: MedmarkRegistry, options: MedmarkOptions): MedmarkRegistryFile | null {
  const site = options.registry?.site;

  if (!site?.url) {
    logger.warn('Skipping sitemap generation: `registry.site.url` is not configured.');
    return null;
  }

  const includeDrafts: boolean = options.registry?.includeDrafts ?? false;
  const urls: string = registry.posts
    .filter((post: MedmarkRegistryEntry) => includeDrafts || !post.draft)
    .map((post: MedmarkRegistryEntry) => {
      const loc: string = joinUrl(site.url!, post.slug);

      return `  <url>
    <loc>${escapeXml(loc)}</loc>
    ${post.date ? `<lastmod>${escapeXml(post.date)}</lastmod>` : ''}
  </url>`;
    })
    .join('\n');

  const content: string = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

  return {
    content,
    filename: 'sitemap.xml',
  };
}

/**
 * Serializes the registry into output files based on the configured formats.
 * Exposed so userland templates can reuse it inside their own
 * `serializeRegistry` hook.
 *
 * @param registry - The aggregated registry.
 * @param context - Context about the run.
 * @returns The files to write, relative to the output root.
 */
export function serializeDefaultRegistry(
  registry: MedmarkRegistry,
  context: MedmarkRegistryContext,
): MedmarkRegistryFile[] {
  const {options} = context;
  const filename: string = options.registry?.filename ?? DEFAULT_MEDMARK_REGISTRY_FILENAME;
  const formats: MedmarkRegistryFormat[] = options.registry?.formats ?? ['json'];

  const files: (MedmarkRegistryFile | null)[] = formats.map((format: MedmarkRegistryFormat) => {
    switch (format) {
      case 'json':
        return serializeAsJson(registry, filename);
      case 'ts':
        return serializeAsTs(registry, filename);
      case 'rss':
        return serializeAsRss(registry, options);
      case 'sitemap':
        return serializeAsSitemap(registry, options);
      default:
        logger.warn(`Unknown registry format "${format}". Skipping.`);
        return null;
    }
  });

  return files.filter((file: MedmarkRegistryFile | null): file is MedmarkRegistryFile => file !== null);
}

/**
 * Singleton that accumulates registry entries across a conversion run.
 * Mirrors the {@link Reporter} pattern.
 */
class RegistryCollector {
  private static instance: RegistryCollector;

  private entries: MedmarkRegistryEntry[];

  private constructor() {
    this.entries = [];
  }

  /**
   * Returns the singleton instance of the RegistryCollector.
   *
   * @returns The RegistryCollector singleton instance.
   */
  static getInstance(): RegistryCollector {
    if (!RegistryCollector.instance) {
      RegistryCollector.instance = new RegistryCollector();
    }

    return RegistryCollector.instance;
  }

  /**
   * Adds an entry to the registry. Ignores `null` (post excluded by the template).
   *
   * @param entry - The registry entry to add.
   */
  add(entry: MedmarkRegistryEntry | null): void {
    if (entry) {
      this.entries.push(entry);
    }
  }

  /**
   * Returns the number of collected entries.
   */
  size(): number {
    return this.entries.length;
  }

  /**
   * Builds the aggregated registry payload.
   *
   * @param generator - The tool + version string (e.g. `medmark@0.2.5`).
   * @param generatedAt - ISO timestamp for the run.
   * @returns The aggregated registry.
   */
  build(generator: string, generatedAt: string): MedmarkRegistry {
    const posts: MedmarkRegistryEntry[] = [...this.entries].sort((a: MedmarkRegistryEntry, b: MedmarkRegistryEntry) =>
      (b.date ?? '').localeCompare(a.date ?? ''),
    );

    return {
      count: posts.length,
      generatedAt,
      generator,
      posts,
      version: MEDMARK_REGISTRY_VERSION,
    };
  }
}

export default RegistryCollector;
