# This workflow builds and deploys the website to GitHub Pages.

name: 🌐 Deploy Website

on:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
        pnpm-version: [latest]
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: 🟢 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🥡 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: ⚙️ Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: 🧩 Install Dependencies
        run: pnpm install

      - name: 🗑️ Remove server-only files
        run: rm apps/website/proxy.ts

      - name: 🏗️ Build Website
        run: pnpm turbo run build --filter=@medmark/website
        env:
          NEXT_EXPORT: "true"
          NEXT_PUBLIC_BASE_PATH: ${{ steps.pages.outputs.base_path }}

      - name: 📤 Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/website/out

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
